os:
- osx
osx_image: xcode7.2
language: generic
env:
  global:
  - 'DEVELOPER_NAME="Mac Distribution: Deco Desktop Production (M5Y2HY4UM2)"'
  - PROFILE_NAME="Deco_Desktop_Production"
  - SIGN_DECO_PACKAGE="true"
  - secure: "Eukpwrzq4POdOPAmU33HstZYGRewCSeBB7lLdM7NR54LP9y6vs2ZpShx3tA7/enLJB0mrhQHUfZVStSOR/JvWef8yAkBGl7P82EaxRBDzEdMKiUSySQ89opKJxozvVLm9BwrUThnrcbxaPA0GmHraY83Rf8DRMOu50npjDe2tRVt1sSSk2ZzTsigyOo9/exXfyRs59hr4ISU/rIbfrlsmCXVXq//p8xTj1euk5oj7JXeogNwIAk/Dqr8yVDfhiwzlnzh3lhvNOKqUu0U4SV1KOdGUM0d5jWSyWewKC7bukM+gBHW7oFqXk+DIovJTQ7aJhjyVDGvwIBWmQHaXrRFe1mqBpvx1tV7d34U0dOp8GoU+qYS+1sMufucovDyHwo1LpRtoi9YI8nKHa0Hj71dMMHvetBLxsorDgUo1XyifrGnm6SDneYSNWzYNaTzLOcBEZqJ0ReI7cx2oKThirGQdE+O+KhtmJO1qLzqkQo3OWMjFBYKeLiM7wzcRJyUdKI0x605w++/u2TOrXMpUCAIwCNTxa/nyrO8IuV5jBnJLA8LRhs8UeFMgP7wF3d6rb1ulvwsd3zyBu5jO4KRMpQ0O8AapYjYf2mDrzXQCPG5PYRfqMm/5RqUJs6vHxySrfqZfNk71f+IUCQnKbVxseX6dFjHlxmZ3zHTPhZP4MJgFCw="
  matrix:
  - NODE_VERSION="5.7"
before_install:
- brew update
- brew install curl
- git clone https://github.com/creationix/nvm.git /tmp/.nvm; source /tmp/.nvm/nvm.sh;
  nvm install $NODE_VERSION; nvm use --delete-prefix $NODE_VERSION;
install:
- "./build/install-dependencies.sh"
script:
- "./build/run-pack.sh"
cache:
  bundler: true
  directories:
  - shared/node_modules
  - desktop/node_modules
  - web/node_modules
deploy:
- provider: s3
  access_key_id: AKIAJETVMVT2MJZNMHCQ
  secret_access_key:
    secure: "ANmoBOs9oDwUyzXGvLOQHx56lXXWzBSsBC4IW25bPCPOII8ONtcrCr9QdWkpWc8SaKebPSunY6HO3oEAmtudKJEymVaAopwC5xMpKbvE6WEhxK86dL9BuczDLR7u1/SMDHGZrsrkJwc4TD9sVwydlg33NIH8xYb8fGTZy6bXS8tAe7L1FQeCiQYxb0P+O7q7ywfkgbRVHc0yUmrIZzsbQovEf7jITXeMbBwAwqPtWUeY5iYVCi+W9WYAgcu0WnJ+GWkaGrucb8aalJD1o5RfSodXBUa7GKOz4JUIoDtTw/3vD4/BIKeVKd1hDRRaLbQBefLUavpvEgh61k33wfByKW+Seq48ylHm7bZ/9dNbIO6jMuV8FNkowZPjf2lINGrtW44mTQjjdpkLpPZT8EhSDWJlXC+UkObQPy9IfDhgZdDZNbC93UUj3iWWDy4x71GqnGdpcuXIPPCAQiIydcYnJN1TJtQ7T0RWFZx83PnYPzqyVEctbMw1AB4ZyhjvZmL7C3v+VqfbwhWuOTmMLbmXaA0emGOlhD4Sul0+KSdF7ddzQ6Rn9LZ0YKfsjusSudg4FiTzg6aBHRkZa2uUyjkWD/9yN6SOygYHRpfIpXj0QHfvr3bwGJqhpCo0EH9gFQvJskv6c54p8A4R0L2ESf4upw2xw0H689O8SFe6GQLiJGg="
  bucket: decopkgs
  skip_cleanup: true
  local_dir: dist
  on:
    branch: release
- provider: s3
  access_key_id: AKIAJETVMVT2MJZNMHCQ
  secret_access_key:
    secure: "ANmoBOs9oDwUyzXGvLOQHx56lXXWzBSsBC4IW25bPCPOII8ONtcrCr9QdWkpWc8SaKebPSunY6HO3oEAmtudKJEymVaAopwC5xMpKbvE6WEhxK86dL9BuczDLR7u1/SMDHGZrsrkJwc4TD9sVwydlg33NIH8xYb8fGTZy6bXS8tAe7L1FQeCiQYxb0P+O7q7ywfkgbRVHc0yUmrIZzsbQovEf7jITXeMbBwAwqPtWUeY5iYVCi+W9WYAgcu0WnJ+GWkaGrucb8aalJD1o5RfSodXBUa7GKOz4JUIoDtTw/3vD4/BIKeVKd1hDRRaLbQBefLUavpvEgh61k33wfByKW+Seq48ylHm7bZ/9dNbIO6jMuV8FNkowZPjf2lINGrtW44mTQjjdpkLpPZT8EhSDWJlXC+UkObQPy9IfDhgZdDZNbC93UUj3iWWDy4x71GqnGdpcuXIPPCAQiIydcYnJN1TJtQ7T0RWFZx83PnYPzqyVEctbMw1AB4ZyhjvZmL7C3v+VqfbwhWuOTmMLbmXaA0emGOlhD4Sul0+KSdF7ddzQ6Rn9LZ0YKfsjusSudg4FiTzg6aBHRkZa2uUyjkWD/9yN6SOygYHRpfIpXj0QHfvr3bwGJqhpCo0EH9gFQvJskv6c54p8A4R0L2ESf4upw2xw0H689O8SFe6GQLiJGg="
  bucket: decopkgs-staging
  skip_cleanup: true
  local_dir: dist
  on:
    branch: staging
- provider: s3
  access_key_id: AKIAJETVMVT2MJZNMHCQ
  secret_access_key:
    secure: "ANmoBOs9oDwUyzXGvLOQHx56lXXWzBSsBC4IW25bPCPOII8ONtcrCr9QdWkpWc8SaKebPSunY6HO3oEAmtudKJEymVaAopwC5xMpKbvE6WEhxK86dL9BuczDLR7u1/SMDHGZrsrkJwc4TD9sVwydlg33NIH8xYb8fGTZy6bXS8tAe7L1FQeCiQYxb0P+O7q7ywfkgbRVHc0yUmrIZzsbQovEf7jITXeMbBwAwqPtWUeY5iYVCi+W9WYAgcu0WnJ+GWkaGrucb8aalJD1o5RfSodXBUa7GKOz4JUIoDtTw/3vD4/BIKeVKd1hDRRaLbQBefLUavpvEgh61k33wfByKW+Seq48ylHm7bZ/9dNbIO6jMuV8FNkowZPjf2lINGrtW44mTQjjdpkLpPZT8EhSDWJlXC+UkObQPy9IfDhgZdDZNbC93UUj3iWWDy4x71GqnGdpcuXIPPCAQiIydcYnJN1TJtQ7T0RWFZx83PnYPzqyVEctbMw1AB4ZyhjvZmL7C3v+VqfbwhWuOTmMLbmXaA0emGOlhD4Sul0+KSdF7ddzQ6Rn9LZ0YKfsjusSudg4FiTzg6aBHRkZa2uUyjkWD/9yN6SOygYHRpfIpXj0QHfvr3bwGJqhpCo0EH9gFQvJskv6c54p8A4R0L2ESf4upw2xw0H689O8SFe6GQLiJGg="
  bucket: decopkgs-bleeding-edge
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
branches:
  only:
  - release
  - staging
  - master
