os:
- osx
osx_image: xcode7.2
language: generic
env:
  global:
  - 'DEVELOPER_NAME="Mac Distribution: Deco Desktop Production (M5Y2HY4UM2)"'
  - PROFILE_NAME="Deco_Desktop_Production"
  - SIGN_DECO_PACKAGE="true"
  - secure: "rwE/dgqO15qwPdPae257rZguw9uayctSjiS7NSpcsSc1KDVl/vY5tJxtFZiIkAQnu8JnqBVHy9bzKbLqfL70h5hGunUBNfG2awFkPAwRhR1518IWHKXTg8LxQqjiR1voQVSXLM5F3zHzOrZyrUb4xU2Ej5PrKBv5yIzvkEZOzVEGp8Lj9wVcHKT4ROy0XvVTwbh03lXsNeiKokaK2pYoDLz+lWF/4P/IdXeQOb4IYNTXN3JpVQewMyQ1jciwVv0Lu+7yJRM2mvOCboDOy1Nvq8/8xNBvZ1ASin0aAy0pgPnmXupDXPavM5w9T1/vPZngOsqWlq1MfknRnni/JXwImEEV4fOHzutlEU/kAg6ytauMN75TeiZtxNu+Urbqwbm4vNF+zTDLdLDtanpvJlOyuZoIFzd8Dun+UXkxADuq+IEQi+GgFB85/CkFvuQB7KK4E+JPqirHUKzVKs3EeTmf1jYFpCCocRrBZPbFt4TeIfFfQoPIDe7lXUpIQNF+/1oYrwXc3EEIl+8ipqYAfOh6OWkRbyU9WtphMjsC78cYewqXN7jq0B8oqcO5jC2jwUPiEareUgtdXs88sBbBnX16TRMyHMDrY/dxqX+P6fy7R7W0ySifruhGe+XzYDOBE0y9UUF6lF9lSdzJidMgMEc5UJyw+Uhd2WJFcWCpItN47Ro="
  matrix:
  - NODE_VERSION="5.7"
before_install:
- brew update
- brew install curl
- git clone https://github.com/creationix/nvm.git /tmp/.nvm; source /tmp/.nvm/nvm.sh;
  nvm install $NODE_VERSION; nvm use --delete-prefix $NODE_VERSION;
install:
- "./build/install-dependencies.sh"
script:
- "./build/run-pack.sh"
cache:
  bundler: true
  directories:
  - shared/node_modules
  - desktop/node_modules
  - web/node_modules
deploy:
- provider: s3
  access_key_id: AKIAJETVMVT2MJZNMHCQ
  secret_access_key:
    secure: "ANmoBOs9oDwUyzXGvLOQHx56lXXWzBSsBC4IW25bPCPOII8ONtcrCr9QdWkpWc8SaKebPSunY6HO3oEAmtudKJEymVaAopwC5xMpKbvE6WEhxK86dL9BuczDLR7u1/SMDHGZrsrkJwc4TD9sVwydlg33NIH8xYb8fGTZy6bXS8tAe7L1FQeCiQYxb0P+O7q7ywfkgbRVHc0yUmrIZzsbQovEf7jITXeMbBwAwqPtWUeY5iYVCi+W9WYAgcu0WnJ+GWkaGrucb8aalJD1o5RfSodXBUa7GKOz4JUIoDtTw/3vD4/BIKeVKd1hDRRaLbQBefLUavpvEgh61k33wfByKW+Seq48ylHm7bZ/9dNbIO6jMuV8FNkowZPjf2lINGrtW44mTQjjdpkLpPZT8EhSDWJlXC+UkObQPy9IfDhgZdDZNbC93UUj3iWWDy4x71GqnGdpcuXIPPCAQiIydcYnJN1TJtQ7T0RWFZx83PnYPzqyVEctbMw1AB4ZyhjvZmL7C3v+VqfbwhWuOTmMLbmXaA0emGOlhD4Sul0+KSdF7ddzQ6Rn9LZ0YKfsjusSudg4FiTzg6aBHRkZa2uUyjkWD/9yN6SOygYHRpfIpXj0QHfvr3bwGJqhpCo0EH9gFQvJskv6c54p8A4R0L2ESf4upw2xw0H689O8SFe6GQLiJGg="
  bucket: decopkgs
  skip_cleanup: true
  local_dir: dist
  on:
    branch: release
- provider: s3
  access_key_id: AKIAJETVMVT2MJZNMHCQ
  secret_access_key:
    secure: "ANmoBOs9oDwUyzXGvLOQHx56lXXWzBSsBC4IW25bPCPOII8ONtcrCr9QdWkpWc8SaKebPSunY6HO3oEAmtudKJEymVaAopwC5xMpKbvE6WEhxK86dL9BuczDLR7u1/SMDHGZrsrkJwc4TD9sVwydlg33NIH8xYb8fGTZy6bXS8tAe7L1FQeCiQYxb0P+O7q7ywfkgbRVHc0yUmrIZzsbQovEf7jITXeMbBwAwqPtWUeY5iYVCi+W9WYAgcu0WnJ+GWkaGrucb8aalJD1o5RfSodXBUa7GKOz4JUIoDtTw/3vD4/BIKeVKd1hDRRaLbQBefLUavpvEgh61k33wfByKW+Seq48ylHm7bZ/9dNbIO6jMuV8FNkowZPjf2lINGrtW44mTQjjdpkLpPZT8EhSDWJlXC+UkObQPy9IfDhgZdDZNbC93UUj3iWWDy4x71GqnGdpcuXIPPCAQiIydcYnJN1TJtQ7T0RWFZx83PnYPzqyVEctbMw1AB4ZyhjvZmL7C3v+VqfbwhWuOTmMLbmXaA0emGOlhD4Sul0+KSdF7ddzQ6Rn9LZ0YKfsjusSudg4FiTzg6aBHRkZa2uUyjkWD/9yN6SOygYHRpfIpXj0QHfvr3bwGJqhpCo0EH9gFQvJskv6c54p8A4R0L2ESf4upw2xw0H689O8SFe6GQLiJGg="
  bucket: decopkgs-staging
  skip_cleanup: true
  local_dir: dist
  on:
    branch: staging
- provider: s3
  access_key_id: AKIAJETVMVT2MJZNMHCQ
  secret_access_key:
    secure: "ANmoBOs9oDwUyzXGvLOQHx56lXXWzBSsBC4IW25bPCPOII8ONtcrCr9QdWkpWc8SaKebPSunY6HO3oEAmtudKJEymVaAopwC5xMpKbvE6WEhxK86dL9BuczDLR7u1/SMDHGZrsrkJwc4TD9sVwydlg33NIH8xYb8fGTZy6bXS8tAe7L1FQeCiQYxb0P+O7q7ywfkgbRVHc0yUmrIZzsbQovEf7jITXeMbBwAwqPtWUeY5iYVCi+W9WYAgcu0WnJ+GWkaGrucb8aalJD1o5RfSodXBUa7GKOz4JUIoDtTw/3vD4/BIKeVKd1hDRRaLbQBefLUavpvEgh61k33wfByKW+Seq48ylHm7bZ/9dNbIO6jMuV8FNkowZPjf2lINGrtW44mTQjjdpkLpPZT8EhSDWJlXC+UkObQPy9IfDhgZdDZNbC93UUj3iWWDy4x71GqnGdpcuXIPPCAQiIydcYnJN1TJtQ7T0RWFZx83PnYPzqyVEctbMw1AB4ZyhjvZmL7C3v+VqfbwhWuOTmMLbmXaA0emGOlhD4Sul0+KSdF7ddzQ6Rn9LZ0YKfsjusSudg4FiTzg6aBHRkZa2uUyjkWD/9yN6SOygYHRpfIpXj0QHfvr3bwGJqhpCo0EH9gFQvJskv6c54p8A4R0L2ESf4upw2xw0H689O8SFe6GQLiJGg="
  bucket: decopkgs-bleeding-edge
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
branches:
  only:
  - release
  - staging
  - master
