#!/bin/bash

set -e

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
cd $ROOT
command -v hyperinstall >/dev/null 2>&1 || {
echo >&2 "Hyperinstall is not in your PATH; run "npm install -g hyperinstall"";
exit 1;
}
hyperinstall install $@
